"""Shared brand system for the AdEngine dashboard — fonts, palette, CSS, Plotly template.

One source of truth so every page renders as one visual system rather than six
independently-styled Streamlit pages. Colors are assigned by job (categorical /
sequential / status), never picked ad hoc per chart — see the module-level
comments next to each constant for which job it serves.
"""
from __future__ import annotations

from pathlib import Path

import plotly.graph_objects as go
import streamlit as st

APP_DIR = Path(__file__).resolve().parent
ROOT_DIR = APP_DIR.parent
LOGO_PATH = ROOT_DIR / "img" / "Project_Black.png"

# ---- Palette -----------------------------------------------------------
# Status / provenance colors (reserved — never reused as a categorical hue).
INK = "#14181A"
INK_SOFT = "#1C2224"
PAPER = "#F5F7F5"
PANEL = "#FFFFFF"
GRAPHITE = "#1D2530"
SLATE = "#64748B"
SLATE_SOFT = "#E2E6EA"
LINE = "#E4E7EB"

OBSERVED = "#0E7C7B"          # status: data read directly from the source
OBSERVED_SOFT = "#E3F3F1"
SYNTHETIC = "#C77D2E"         # status: generated by the ADR-002 synthetic layer
SYNTHETIC_SOFT = "#FBEEE0"
MODELED = "#6C5CE7"           # status: output of a fitted estimator
MODELED_SOFT = "#EEEBFC"
RISK = "#B0402E"              # status: needs attention
RISK_SOFT = "#F7E7E3"
LIME = "#D8FB4C"              # brand accent — highlights only, never a data hue
LIME_DEEP = "#BFE637"
BLUE = "#2E86AB"

# Categorical theme, fixed order — reused for segments (5) and channels (4),
# always assigned by entity identity, never by rank.
CATEGORICAL = [OBSERVED, BLUE, MODELED, SYNTHETIC, "#94A3B8", "#B0402E"]

SEGMENT_COLORS = {
    "Champions": OBSERVED,
    "Loyal Customers": BLUE,
    "Potential Loyalists": MODELED,
    "At Risk": SYNTHETIC,
    "Hibernating": "#94A3B8",
}
CHANNEL_COLORS = {
    "paid_search": BLUE,
    "paid_social": MODELED,
    "email": OBSERVED,
    "display": SYNTHETIC,
}
CHANNEL_LABELS = {
    "paid_search": "Paid Search",
    "paid_social": "Paid Social",
    "email": "Email",
    "display": "Display",
}

FONT_DISPLAY = "'Space Grotesk', sans-serif"
FONT_BODY = "'IBM Plex Sans', sans-serif"
FONT_MONO = "'IBM Plex Mono', monospace"


def inject_css() -> None:
    css = "".join([
        '<link rel="preconnect" href="https://fonts.googleapis.com">',
        '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
        '<link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;600;700&family=IBM+Plex+Sans:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500;600&display=swap" rel="stylesheet">',
        "<style>",
        f'html, body, [class*="css"] {{ font-family: {FONT_BODY}; }}',
        f'h1, h2, h3, .ade-display {{ font-family: {FONT_DISPLAY}; letter-spacing: -0.01em; }}',
        f'.ade-mono {{ font-family: {FONT_MONO}; }}',
        f'section[data-testid="stSidebar"] {{ background: {PANEL}; border-right: 1px solid {LINE}; }}',
        f'section[data-testid="stSidebar"] * {{ font-family: {FONT_BODY}; }}',
        '.block-container { padding-top: 2rem; max-width: 1440px; }',
        '.ade-tag { font-family: ' + FONT_MONO + '; font-size: 10.5px; font-weight: 600; text-transform: uppercase; '
        'letter-spacing: 0.04em; padding: 3px 9px; border-radius: 6px; white-space: nowrap; display: inline-block; }',
        f'.ade-tag--observed {{ background: {OBSERVED_SOFT}; color: {OBSERVED}; }}',
        f'.ade-tag--synthetic {{ background: {SYNTHETIC_SOFT}; color: {SYNTHETIC}; }}',
        f'.ade-tag--modeled {{ background: {MODELED_SOFT}; color: {MODELED}; }}',
        f'.ade-tag--risk {{ background: {RISK_SOFT}; color: {RISK}; }}',
        f'.ade-hero {{ background: {INK}; color: {PAPER}; border-radius: 18px; padding: 26px 28px 22px; '
        'position: relative; overflow: hidden; margin-bottom: 4px; }',
        '.ade-hero::after { content:""; position:absolute; top:-60%; right:-10%; width:280px; height:280px; border-radius:50%; '
        'background: radial-gradient(circle, rgba(216,251,76,0.14), transparent 70%); pointer-events:none; }',
        f'.ade-hero__label {{ font-family: {FONT_MONO}; font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em; color: rgba(244,246,243,0.58); }}',
        f'.ade-hero__value {{ font-family: {FONT_DISPLAY}; font-weight: 700; font-size: 40px; margin: 8px 0 6px; }}',
        '.ade-hero__sub { font-size: 13px; color: rgba(244,246,243,0.62); }',
        f'.ade-hero__sub b {{ color: {PAPER}; font-family: {FONT_MONO}; font-weight: 500; }}',
        f'.ade-stat {{ background: {PANEL}; border: 1px solid {LINE}; border-radius: 16px; padding: 18px 20px; '
        'height: 100%; display:flex; flex-direction:column; justify-content:center; }',
        f'.ade-stat__label {{ font-family: {FONT_MONO}; font-size: 11px; text-transform: uppercase; letter-spacing: 0.04em; color: {SLATE}; margin-bottom: 8px; }}',
        f'.ade-stat__value {{ font-family: {FONT_DISPLAY}; font-size: 24px; font-weight: 700; color: {INK}; }}',
        '.ade-stat__delta { font-size: 12px; margin-top: 6px; font-weight: 600; }',
        f'.ade-stat__delta--up {{ color: {OBSERVED}; }}',
        f'.ade-stat__delta--down {{ color: {RISK}; }}',
        f'.ade-callout {{ background: {PANEL}; border: 1px solid {LINE}; border-left: 3px solid {MODELED}; '
        f'border-radius: 10px; padding: 14px 16px; font-size: 13.5px; color: {GRAPHITE}; margin: 10px 0 16px; }}',
        f'.ade-callout b {{ color: {INK}; }}',
        f'.ade-disclaimer {{ display:flex; gap:12px; align-items:flex-start; background: {SYNTHETIC_SOFT}; '
        'border: 1px solid rgba(199,125,46,0.3); border-radius: 10px; padding: 14px 16px; '
        'margin-bottom: 14px; font-size: 13.5px; color: #6b4517; }',
        '.ade-disclaimer b { color: #4d3110; }',
        f'.ade-section-eyebrow {{ font-family: {FONT_MONO}; font-size: 11px; text-transform: uppercase; letter-spacing: 0.06em; color: {SLATE}; margin-bottom: 4px; }}',
        f'div[data-testid="stMetric"] {{ background: {PANEL}; border: 1px solid {LINE}; border-radius: 16px; padding: 14px 18px; }}',
        f'div[data-testid="stMetricLabel"] {{ font-family: {FONT_MONO}; font-size: 11.5px; text-transform: uppercase; color: {SLATE}; }}',
        f'div[data-testid="stMetricValue"] {{ font-family: {FONT_DISPLAY}; color: {INK}; }}',
        "</style>",
    ])
    st.markdown(css, unsafe_allow_html=True)


def render_sidebar_brand() -> None:
    if LOGO_PATH.exists():
        st.logo(str(LOGO_PATH))


def tag(label: str, kind: str) -> str:
    return f'<span class="ade-tag ade-tag--{kind}">{label}</span>'


def hero_card(label: str, value: str, sub_html: str, live_tag: str | None = None) -> str:
    live = f'<span class="ade-mono" style="color:{LIME};font-size:11px;">&#9679; {live_tag}</span>' if live_tag else ""
    return (
        f'<div class="ade-hero"><div class="ade-hero__label">{label} {live}</div>'
        f'<div class="ade-hero__value">{value}</div>'
        f'<div class="ade-hero__sub">{sub_html}</div></div>'
    )


def stat_card(label_html: str, value: str, delta_html: str = "") -> str:
    delta = f'<div class="ade-stat__delta">{delta_html}</div>' if delta_html else ""
    return (
        f'<div class="ade-stat"><div class="ade-stat__label">{label_html}</div>'
        f'<div class="ade-stat__value">{value}</div>{delta}</div>'
    )


def callout(html: str) -> str:
    return f'<div class="ade-callout">{html}</div>'


def disclaimer(html: str) -> str:
    return f'<div class="ade-disclaimer"><span>&#9888;</span><div>{html}</div></div>'


# ---- Plotly template -----------------------------------------------------
def plotly_template() -> go.layout.Template:
    return go.layout.Template(
        layout=go.Layout(
            font=dict(family=FONT_MONO, size=12, color=SLATE),
            title=dict(font=dict(family=FONT_DISPLAY, size=15, color=INK)),
            paper_bgcolor=PANEL,
            plot_bgcolor=PANEL,
            colorway=CATEGORICAL,
            xaxis=dict(gridcolor=LINE, zerolinecolor=LINE, linecolor=LINE, tickfont=dict(color=SLATE), automargin=True),
            yaxis=dict(gridcolor=LINE, zerolinecolor=LINE, linecolor=LINE, tickfont=dict(color=SLATE), automargin=True),
            legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0, font=dict(size=11)),
            margin=dict(l=10, r=10, t=40, b=10, autoexpand=True),
            hoverlabel=dict(bgcolor=INK, font=dict(color=PAPER, family=FONT_MONO, size=12)),
        )
    )


def apply_plotly_theme(fig: go.Figure, height: int | None = None) -> go.Figure:
    fig.update_layout(template=plotly_template())
    if height:
        fig.update_layout(height=height)
    return fig
