from __future__ import annotations

import sys
from pathlib import Path

import plotly.graph_objects as go
import streamlit as st

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import data_loader as dl
import theme

st.set_page_config(page_title="AdEngine — Media Metrics Engine", page_icon="📊", layout="wide")
theme.inject_css()
theme.render_sidebar_brand()

if not dl.data_available():
    st.error("No pipeline artifacts found in data/marts/. Run `make pipeline && make train` first.")
    st.stop()

channel_metrics = dl.load_parquet("channel_metrics")
retention = dl.load_parquet("cohort_retention_matrix")
revenue_matrix = dl.load_parquet("cohort_revenue_matrix")
ltv_table = dl.load_parquet("ltv_table")

st.markdown(
    '<p class="ade-section-eyebrow">Page 4 of 6 · CPA · LTV · ROAS · cohort retention</p>'
    '<h1 style="margin-bottom:2px;">Media Metrics Engine</h1>'
    f'<p style="color:{theme.SLATE};font-size:13.5px;max-width:680px;">'
    'Which channels convert efficiently, and how does customer value accumulate after acquisition?</p>',
    unsafe_allow_html=True,
)

st.markdown(theme.disclaimer(
    '<b>Synthetic layer, ADR-002.</b> Online Retail II has no channel or cost data. Channel, spend, and campaign-exposure '
    'fields on this page are generated by a parameterized probabilistic rule set (configs/attribution.yaml) to exercise the '
    'metrics engine end-to-end — they are not observed media performance and must never be reported as such.'
), unsafe_allow_html=True)

channel_metrics = channel_metrics.copy()
channel_metrics["channel_label"] = channel_metrics["channel"].map(theme.CHANNEL_LABELS)
best = channel_metrics.sort_values("roas", ascending=False).iloc[0]

col1, col2 = st.columns([1.7, 1], gap="medium")
with col1:
    total_spend = channel_metrics["spend_synthetic"].sum()
    stage_bar = "".join(
        f'<div style="height:100%;width:{100*s/total_spend:.1f}%;background:{theme.CHANNEL_COLORS[c]};"></div>'
        for c, s in zip(channel_metrics["channel"], channel_metrics["spend_synthetic"])
    )
    legend = "".join(
        f'<div style="display:flex;align-items:center;gap:6px;font-size:12px;color:rgba(244,246,243,0.62);">'
        f'<span style="width:8px;height:8px;border-radius:2px;background:{theme.CHANNEL_COLORS[c]};flex-shrink:0;"></span>{theme.CHANNEL_LABELS[c]} · '
        f'<b class="ade-mono" style="color:{theme.PAPER};">{r:.1f}&times;</b></div>'
        for c, r in zip(channel_metrics["channel"], channel_metrics["roas"])
    )
    st.markdown(
        f'<div class="ade-hero"><div class="ade-hero__label">Top channel spotlight '
        f'<span class="ade-mono" style="color:{theme.LIME};font-size:11px;">&#9679; {best["channel_label"].lower()}</span></div>'
        f'<div class="ade-hero__value">{best["roas"]:.1f}&times;</div>'
        f'<div class="ade-hero__sub">{best["channel_label"]} · <b>£{best["cpa"]:.2f}</b> CPA · <b>{best["ltv_cac"]:.1f}&times;</b> LTV:CAC</div>'
        f'<div style="height:10px;border-radius:6px;overflow:hidden;background:rgba(244,246,243,0.08);display:flex;margin:12px 0;">{stage_bar}</div>'
        f'<div style="display:flex;flex-wrap:wrap;gap:14px;">{legend}</div></div>',
        unsafe_allow_html=True,
    )
with col2:
    st.markdown(theme.stat_card('Best ROAS Channel <span class="ade-tag ade-tag--synthetic">Synthetic</span>', best["channel_label"], f'{best["roas"]:.1f}&times; revenue per £ spent (90d window)'), unsafe_allow_html=True)
    st.write("")
    best_ltv = channel_metrics.sort_values("ltv_cac", ascending=False).iloc[0]
    st.markdown(theme.stat_card('Best LTV:CAC <span class="ade-tag ade-tag--synthetic">Synthetic</span>', theme.CHANNEL_LABELS[best_ltv["channel"]], f'{best_ltv["ltv_cac"]:.1f}&times; ratio'), unsafe_allow_html=True)

st.write("")
c1, c2, c3 = st.columns(3, gap="medium")
with c1:
    st.markdown(f'<p class="ade-section-eyebrow">Which channel costs least per acquisition?</p><h4 style="margin-top:0;">CPA by Channel {theme.tag("Synthetic", "synthetic")}</h4>', unsafe_allow_html=True)
    fig = go.Figure(go.Bar(x=channel_metrics["channel_label"], y=channel_metrics["cpa"], marker_color=[theme.CHANNEL_COLORS[c] for c in channel_metrics["channel"]], hovertemplate="%{x}: £%{y:.2f}<extra></extra>"))
    fig.update_yaxes(title="CPA (£)")
    theme.apply_plotly_theme(fig, height=280)
    st.plotly_chart(fig, use_container_width=True, theme=None, config={"displayModeBar": False})
with c2:
    st.markdown(f'<p class="ade-section-eyebrow">Which channel returns most per £ spent?</p><h4 style="margin-top:0;">ROAS by Channel {theme.tag("Synthetic", "synthetic")}</h4>', unsafe_allow_html=True)
    fig = go.Figure(go.Bar(x=channel_metrics["channel_label"], y=channel_metrics["roas"], marker_color=[theme.CHANNEL_COLORS[c] for c in channel_metrics["channel"]], hovertemplate="%{x}: %{y:.1f}&times;<extra></extra>"))
    fig.update_yaxes(title="ROAS (90d window)")
    theme.apply_plotly_theme(fig, height=280)
    st.plotly_chart(fig, use_container_width=True, theme=None, config={"displayModeBar": False})
with c3:
    st.markdown(f'<p class="ade-section-eyebrow">Is acquisition cost justified long-run?</p><h4 style="margin-top:0;">LTV : CAC by Channel {theme.tag("Synthetic", "synthetic")}</h4>', unsafe_allow_html=True)
    fig = go.Figure(go.Bar(x=channel_metrics["channel_label"], y=channel_metrics["ltv_cac"], marker_color=[theme.CHANNEL_COLORS[c] for c in channel_metrics["channel"]], hovertemplate="%{x}: %{y:.1f}&times;<extra></extra>"))
    fig.add_hline(y=3, line_dash="dash", line_color=theme.RISK, annotation_text="3× efficiency benchmark", annotation_font_size=10)
    fig.update_yaxes(title="LTV : CAC")
    theme.apply_plotly_theme(fig, height=280)
    st.plotly_chart(fig, use_container_width=True, theme=None, config={"displayModeBar": False})
st.caption("ROAS uses revenue realized within the same 90-day target window as conversions (an apples-to-apples short-term efficiency read); LTV:CAC intentionally compares a 12-month BG/NBD-projected value against a one-time acquisition cost, so it is expected to run much larger than ROAS — that gap is the whole point of separating the two metrics.")

st.write("")
st.markdown(f'<h4 style="margin-top:0;">LTV Methodology {theme.tag("Modeled", "modeled")}</h4>', unsafe_allow_html=True)
method = ltv_table["ltv_method"].iloc[0]
st.markdown(
    f'<div class="ade-callout"><b>Method in use: {"BG/NBD + Gamma-Gamma" if method=="bgnbd_gamma_gamma" else "Heuristic fallback"}</b><br>'
    'Two layers, in order of maturity: <b>(1) Historical cohort LTV</b> — cumulative observed revenue per acquisition-month '
    'cohort, read directly from actual purchase history (the reference, no assumptions). '
    '<b>(2) Probabilistic LTV</b> — BG/NBD for expected future transactions + Gamma-Gamma for expected order value, via the '
    '<code>lifetimes</code> library, projected 12 months forward. Because <code>lifetimes</code> is not under active '
    'maintenance, a documented heuristic (AOV × annual frequency × gross margin × horizon) is the automatic fallback if the '
    'fit fails — see <code>metrics.fit_bgnbd_gamma_gamma</code>.</div>',
    unsafe_allow_html=True,
)

st.write("")
st.markdown(
    f'<p class="ade-section-eyebrow">Which acquisition cohorts retain best?</p>'
    f'<h4 style="margin-top:0;">Monthly Cohort Retention Matrix {theme.tag("Observed", "observed")}</h4>',
    unsafe_allow_html=True,
)
month_cols = [c for c in retention.columns if c.startswith("M")]
z = retention[month_cols].to_numpy(dtype=float)
fig = go.Figure(go.Heatmap(
    z=z, x=month_cols, y=retention["acquisition_cohort"], colorscale=[[0, "#EEF0EE"], [1, theme.OBSERVED]],
    hovertemplate="Cohort %{y}, %{x}: %{z:.1f}%%<extra></extra>",
    colorbar=dict(title="% active", ticksuffix="%", outlinewidth=0, tickfont=dict(color=theme.SLATE)),
    xgap=3, ygap=3,
))
fig.update_yaxes(autorange="reversed", title="Acquisition cohort")
theme.apply_plotly_theme(fig, height=320)
st.plotly_chart(fig, use_container_width=True, theme=None, config={"displayModeBar": False})
st.caption("Blank cells have not yet reached that month-since-acquisition as of T_test — this is censoring, not missing data, and is handled explicitly rather than imputed.")

st.write("")
st.markdown('<h4 style="margin-top:0;">Channel Performance Table</h4>', unsafe_allow_html=True)
display = channel_metrics.rename(columns={
    "channel_label": "Channel", "customers": "Customers", "spend_synthetic": "Spend (£, synthetic)",
    "conversions": "Conversions (90d)", "revenue": "Window Revenue (£)", "cpa": "CPA (£)", "roas": "ROAS",
    "avg_cac": "Avg. CAC (£)", "avg_ltv": "Avg. LTV, 12mo (£)", "ltv_cac": "LTV:CAC",
})[["Channel", "Customers", "Spend (£, synthetic)", "Conversions (90d)", "Window Revenue (£)", "CPA (£)", "ROAS", "Avg. CAC (£)", "Avg. LTV, 12mo (£)", "LTV:CAC"]]
st.dataframe(display, hide_index=True, use_container_width=True)

csv = display.to_csv(index=False).encode("utf-8")
st.download_button("Export channel metrics (CSV)", csv, "adengine_channel_metrics.csv", "text/csv")

st.markdown("---")
st.caption("Channels: Paid Search · Paid Social · Email · Display (all synthetic, ADR-002) · Retention = % of cohort with ≥1 order that month")
